apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: ch_datasource
    access: proxy
    url: http://clickhouse_srv:8123
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: movie_analytics
      port: 8123
      server: clickhouse_srv
      username: default
      protocol: http
      tlsSkipVerify: true
    secureJsonData:
      password: ""